### ISSUE TITLE
Cut black borders

### ISSUE THREAD

**Issue by smc8050** [z80z80z80/autocrop#4]
Hi,
I just stumbled uppon your very cool script:) Would it also be possible to cut black borders?
Which variables would have to be changed for this? I looked at the code but my python is to basic to fully understand it. I assume it would be somewhere in the `cont` function?
I am digitizing old dias for my mother and they look as follows: 
![DSC_00324.JPG](https://user-images.githubusercontent.com/27972967/104651793-6eee1500-56b8-11eb-8602-969f39a27e5b.jpg)

Thank your for your work done with this script, and I would be very happy to hear from you :)

**Comment by z80z80z80** [comment]
Hi! 

Thank you for your feature recommendation. I tried to address this in my latest commit https://github.com/z80z80z80/autocrop/commit/a49f66c1551047e4328d02960a599ded4fcdd049. 

However, this still doesn't work for your example because of the halo-like effect in the top-left corner which overlaps with the black border. I still encourage you to try the latest version if this issue isn't present on all of your scans. It might even work in most cases and then you can just crop the few images that remain by hand.

**Comment by smc8050** [comment]
Hi,
Thank you for your update, however you were right it does not work with the unclear borders. Unfortunately most of the photos have this effect. But I have found another code snippet on the internet which makes it work. Until now my code is pretty ugly but works, I can send you an update if you want to have a look at it. But it's not based on your code so I don't know if it helps you.

**Comment by z80z80z80** [comment]
I’d love to see your approach. It’s always good to learn new ways of solving a problem. And maybe I can integrate it into the code as an alternative algorithm for cases like yours :)

**Comment by smc8050** [comment]
Hi,
So I uploaded my files on Github [here](https://github.com/smc8050/Dias_Autocrop) if you want to have a look, it does not rotate and scale the image as your script and is not as fancy. But for my purpose it was good enough(as I am no pro). I also implemented a control condition, which checks for possible crop failures and exports it to a separate folder for manual review.

**Comment by z80z80z80** [comment]
That's a nice solution, thanks for sharing. But you were right, it doesn't integrate well into my approach. However, I'd like to add a link to your repository in the README.md if you don't mind. :)

**Comment by smc8050** [comment]
Yes sure, I think I will do the same with yours ;)
