### ISSUE TITLE
Is there any other reference or code for autocropping, since this code is not working on all kinds of images

### ISSUE THREAD

**Issue by BakingBrains** [z80z80z80/autocrop#5]

**Comment by z80z80z80** [comment]
What exactly is not working? If there are any error messages, please share them so we can try to find a solution. 

Also, examples of the kind of images that don't work would be awesome :)

**Comment by aleks-mariusz** [comment]
i have a set of old photos scanned - they have a solid white background (the white is because my scanner software padded the image to be a certain size), AND a grey background (the grey is the bed part of the scanner).. so i figure i'd run it through autocrop with two passes - once to get rid of the white, which it did well, but then i can't seem to get rid of the grey part as well.. here's the same sample image - once before and once after with just the grey background.. running it a 2nd time results in the same image with the grey background.. 

![Scan 105](https://user-images.githubusercontent.com/2719694/113457512-e43fcb00-9407-11eb-9085-9978f87a4f9f.jpeg)

and after the first pass

![Scan 105](https://user-images.githubusercontent.com/2719694/113457548-fde11280-9407-11eb-8d75-e0bf3d6e194f.jpeg)

**Comment by z80z80z80** [comment]
Hey aleks,

Unfortunately I couldn't find a solution to this. The problem lies in the rounded edges, which my algorithm can't comprehend (hence the first run works as expected).
I'm currently working on an additional AI feature which would (hopefully) work on all those cases that don't work out of the box at the moment.

Little heads up however - you'll get somewhat of a result if you do:
- increase the contrast of the image after the first run (to get a white background)
- invert it
- feed it to [this algorithm](https://github.com/smc8050/Dias_Autocrop) 
- invert the output
- decrease the contrast

ImageMagick can do the contrast adjustment and inverting steps for you using `convert`.
