### ISSUE TITLE
Does This Python Auto Cropping Tool Work with RAW (CR2) Captures?

### ISSUE THREAD

**Issue by vepicurean** [z80z80z80/autocrop#6]
These are questions before I start experimenting with this autocropping tool.  It was not clear in the description on these items.  

Does this work with RAW (Canon CR2) input files? Can the tool produce JPG and preferably TIFF output files on the cropped images?

How fast (cropped files per minute)? 

Thanks for your help and time.

**Comment by z80z80z80** [comment]
RAW support is not implemented but possible: https://stackoverflow.com/a/68669964. I won't implement this at the moment because it would add another dependency. I'd suggest doing processing into TIFF first and then using autocrop.

At the moment the output file format will be the same as the input format (for supported formats see: https://github.com/z80z80z80/autocrop/blob/master/autocrop.py#L214)

Speed depends heavily on the resolution, your CPU and if the threshold needs to be adjusted. So I really can't make any estimations. But for an idea: on an Intel i5 mobile CPU from 2013 36 images took only a few seconds.

**Comment by vepicurean** [comment]
Hi:

Thanks for your additional information. Appreciated. 

We always cropped the RAW files (we always capture RAW), and then export to the require working file format (usually TIFF, but not always). It's how most institutional work flows go. 

Hardware based processing power is not an issue. We have professional grade Mac and/or Windows workstations. We prefer to do the post processing work on MacOS.
